version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /icons
  static_dir: icons
- url: /stylesheets
  static_dir: stylesheets
- url: /.*
  script: picker.app


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest